FROM rust:1.98.0-trixie@sha256:620dbcd124499c59e2406d3741574b5c5838cf9eb9656f0c3a03948f79b02959

ARG TPM2_TSS_VERSION=506c5e6db0c8514f321dc16a0da2580483f3df04   # version 4.2.0

RUN rustup component add rustfmt clippy \
    && cargo install --locked cargo-rdme \
    && cargo install --locked cargo-llvm-cov

RUN apt-get update && apt-get install -y --no-install-recommends \
        autoconf \
        autoconf-archive \
        automake \
        build-essential \
        ca-certificates \
        curl \
        doxygen \
        git \
        gnupg \
        libcmocka-dev \
        libcmocka0 \
        libcurl4-openssl-dev \
        libftdi-dev \
        libini-config-dev \
        libjson-c-dev \
        libltdl-dev \
        libssl-dev \
        libtool \
        libusb-1.0-0-dev \
        man \
        pkg-config \
        swtpm \
        swtpm-tools \
        uthash-dev \
        uuid-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --filter=blob:none https://github.com/tpm2-software/tpm2-tss /tmp/tpm2-tss \
    && cd /tmp/tpm2-tss \
    && git checkout "${TPM2_TSS_VERSION}" \
    && ./bootstrap \
    && ./configure --prefix=/usr --disable-fapi --disable-weakcrypto --disable-integration \
    && make -j"$(nproc)" \
    && make install \
    && ldconfig \
    && rm -rf /tmp/tpm2-tss

WORKDIR /workspaces/rust-tpm2-cli
