FROM rust:1.95@sha256:4a7e3a0c309c9bab658e469f842711bd595fae484936bc5d605e08ca0c631bf4

ARG TPM2_TSS_VERSION=30e6057722058cb85c292dcb7b77760ad6410d4e   # version 4.1.3

RUN rustup component add rustfmt clippy && cargo install cargo-rdme

RUN apt-get update && apt-get install -y --no-install-recommends \
        autoconf autoconf-archive automake build-essential ca-certificates curl \
        doxygen git gnupg libcmocka-dev libcmocka0 libcurl4-openssl-dev libftdi-dev \
        libini-config-dev libjson-c-dev libltdl-dev libssl-dev libtool libusb-1.0-0-dev \
        pkg-config swtpm swtpm-tools uthash-dev uuid-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --filter=blob:none https://github.com/tpm2-software/tpm2-tss /tmp/tpm2-tss \
    && cd /tmp/tpm2-tss \
    && git checkout "${TPM2_TSS_VERSION}" \
    && ./bootstrap \
    && ./configure --prefix=/usr --disable-fapi --disable-weakcrypto --disable-integration \
    && make -j"$(nproc)" \
    && make install \
    && ldconfig \
    && rm -rf /tmp/tpm2-tss

WORKDIR /workspaces/rust-tpm2-cli
