// SPDX-License-Identifier: Apache-2.0

use clap::{Parser, Subcommand};
use std::collections::BTreeSet;
use std::ffi::OsStr;
use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};

const GENERATED_HEADER: &[u8] = b".\\\" Generated by cargo xtask manpages; do not edit.\n";

#[derive(Parser)]
#[command(name = "xtask", bin_name = "cargo xtask")]
struct Xtask {
    #[command(subcommand)]
    task: Task,
}

#[derive(Subcommand)]
enum Task {
    /// Generate man pages from the clap command definitions.
    #[command(alias = "man", alias = "man-pages")]
    Manpages {
        /// Output directory (defaults to target/man in the workspace).
        #[arg(long, value_name = "DIR")]
        out_dir: Option<PathBuf>,
    },
}

fn main() -> io::Result<()> {
    match Xtask::parse().task {
        Task::Manpages { out_dir } => generate_manpages(out_dir),
    }
}

fn generate_manpages(out_dir: Option<PathBuf>) -> io::Result<()> {
    let out_dir = out_dir.unwrap_or_else(|| workspace_root().join("target/man"));
    fs::create_dir_all(&out_dir)?;

    let staging_dir = tempfile::tempdir_in(&out_dir)?;
    clap_mangen::generate_to(tpm2_cli::command(), staging_dir.path())?;

    let generated_names = fs::read_dir(staging_dir.path())?
        .map(|entry| entry.map(|entry| entry.file_name()))
        .collect::<io::Result<BTreeSet<_>>>()?;

    let prepared_pages = generated_names
        .iter()
        .map(|name| {
            let staged_page = staging_dir.path().join(name);
            let contents = fs::read(&staged_page)?;
            let mut page = tempfile::NamedTempFile::new_in(staging_dir.path())?;
            page.write_all(GENERATED_HEADER)?;
            page.write_all(&contents)?;
            page.as_file()
                .set_permissions(fs::metadata(staged_page)?.permissions())?;
            Ok((name.clone(), page))
        })
        .collect::<io::Result<Vec<_>>>()?;

    for (name, page) in prepared_pages {
        page.persist(out_dir.join(name))
            .map_err(|error| error.error)?;
    }

    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let name = entry.file_name();
        let file_type = entry.file_type()?;
        if file_type.is_file()
            && is_manpage_name(&name)
            && !generated_names.contains(&name)
            && has_generated_header(&entry.path())?
        {
            fs::remove_file(entry.path())?;
        }
    }

    println!("Generated man pages in {}", out_dir.display());
    Ok(())
}

fn is_manpage_name(name: &OsStr) -> bool {
    name == OsStr::new("tpm2.1")
        || name
            .to_str()
            .is_some_and(|name| name.starts_with("tpm2-") && name.ends_with(".1"))
}

fn has_generated_header(path: &Path) -> io::Result<bool> {
    let mut header = vec![0; GENERATED_HEADER.len()];
    match File::open(path)?.read_exact(&mut header) {
        Ok(()) => Ok(header == GENERATED_HEADER),
        Err(error) if error.kind() == io::ErrorKind::UnexpectedEof => Ok(false),
        Err(error) => Err(error),
    }
}

fn workspace_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask must be located directly below the workspace root")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn visible_command_count(command: &clap::Command) -> usize {
        1 + command
            .get_subcommands()
            .filter(|subcommand| !subcommand.is_hide_set())
            .map(visible_command_count)
            .sum::<usize>()
    }

    #[test]
    fn generates_root_and_subcommand_manpages() {
        let output = tempfile::tempdir().expect("temporary directory should be created");

        generate_manpages(Some(output.path().to_path_buf()))
            .expect("man pages should be generated");

        let generated_count = fs::read_dir(output.path())
            .expect("output directory should be readable")
            .filter_map(Result::ok)
            .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "1"))
            .count();
        let expected_count = visible_command_count(&tpm2_cli::command());

        assert_eq!(generated_count, expected_count);

        for name in ["tpm2.1", "tpm2-getrandom.1"] {
            let page = fs::read_to_string(output.path().join(name))
                .expect("generated man page should be readable");
            assert!(page.contains(".SH NAME"));
            assert!(page.contains(".SH SYNOPSIS"));
        }
    }

    #[test]
    fn removes_only_stale_manpages_generated_by_xtask() {
        let output = tempfile::tempdir().expect("temporary directory should be created");
        let stale_page = output.path().join("tpm2-obsolete.1");
        let foreign_page = output.path().join("tpm2-custom.1");
        let unrelated_page = output.path().join("another-tool.1");
        fs::write(&stale_page, GENERATED_HEADER).expect("stale page should be created");
        fs::write(&foreign_page, "foreign").expect("foreign page should be created");
        fs::write(&unrelated_page, "unrelated").expect("unrelated page should be created");

        generate_manpages(Some(output.path().to_path_buf()))
            .expect("man pages should be generated");

        assert!(!stale_page.exists());
        assert!(foreign_page.is_file());
        assert!(unrelated_page.is_file());
    }
}
