name: SPDX License Check

on:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/spdx.yml"
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/spdx.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: enarx/spdx@d4020ee98e3101dd487c5184f27c6a6fb4f88709 # master
        with:
          licenses: Apache-2.0
