name: Test

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/actions/install-tpm2-tss/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/actions/install-tpm2-tss/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - "1.90.0"
          - stable
        os-arch:
          - ubuntu-24.04-x86_64
          - ubuntu-24.04-aarch64
        include:
          - os-arch: ubuntu-24.04-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-arch: ubuntu-24.04-aarch64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - uses: ./.github/actions/install-tpm2-tss
      # - run: sudo apt-get update && sudo apt-get install -y libtss2-dev pkg-config
      - name: Install swtpm
        run: sudo apt-get install -y swtpm
      - name: Run cargo test --all-targets
        env:
          TSS2_ESYS_STATIC: 1
          TSS2_SYS_STATIC: 1
          TSS2_MU_STATIC: 1
          TSS2_TCTILDR_STATIC: 1
        run: cargo test --all-targets
